# Constants
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 700
SCREEN_TITLE = "Space Invaders"
SPRITE_SCALE_ALIENS = 1.5
SPRITE_SCALE_SHIP = 1.5
SPRITE_SCALE_BULLET = 0.5
SPRITE_SCALE_SHIELD = 1
SPRITE_SCALE_BONUS_ALIEN = 0.04
RIGHT = 0
LEFT = 1
ALIEN_STEP = 5
PLAYER_BULLET_SPEED = 500
ALIEN_BULLET_SPEED = -350
SHIELD_WIDTH = 100
BONUS_ALIEN_CHANCE = 300
